version: "3.5"

services:
  app_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    depends_on:
      - db
      - nginx
      - certbot
    env_file:
      - .env
    ports:
      - "8080:8080"
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=timecodes_db
    ports:
      - 9000:5432
  nginx:
    image: nginx:latest
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./support/nginx:/etc/nginx/conf.d
      - ./support/certbot/conf:/etc/letsencrypt
      - ./support/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./support/certbot/conf:/etc/letsencrypt
      - ./support/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
