version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.livereload
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - PORT=8080
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_HOST=db
      - PG_PORT=5432
      - PG_DB=youanno
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=youanno
    ports:
      - 9000:5432
