name: Essential checks
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@master
      - name: Run GolangCI-Lint Action
        uses: actions-contrib/golangci-lint@v1
        with:
          args: run --exclude-use-default
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@master
      - name: docker-compose version
        run: docker-compose --version
      - name: Build docker image
        run: |
          cp .env.example .env
          docker-compose build app_test
      - name: Run tests
        run: docker-compose run app_test go test ./... -covermode=count -coverprofile=coverage.out
      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1.0.2
        with:
            infile: coverage.out
            outfile: coverage.lcov
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
            github-token: ${{ secrets.github_token }}
            path-to-lcov: coverage.lcov
