name: Run PR checks
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@master
      - name: Run GolangCI-Lint Action
        uses: actions-contrib/golangci-lint@v1
        with:
          args: run --exclude-use-default
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@master
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - name: Run go test
        run: |
          go mod download
          go test ./... -cover
