name: Deploy to Digital Ocean
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: ssh key passphrase
        uses: appleboy/ssh-action@master
        env:
          DEPLOY_PASSWORD: ${{ secrets.PASSWORD }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          passphrase: ${{ secrets.PASSPHRASE }}
          key: ${{ secrets.PRIVATE_KEY }}
          envs: DEPLOY_PASSWORD
          script: |
            cd /home/deploy/applications/timecodes/timecodes-api
            git checkout master
            git pull
            echo $DEPLOY_PASSWORD | sudo -S docker-compose build app
            echo $DEPLOY_PASSWORD | sudo -S docker-compose up -d app
